
parking:
    capacite_max: 8

# le tkinter viendra chercher ces infos ici:
security:
    code_secret: "1234567"
    admin_password: "8888888"
    super_admin_password: "5555555"
    max_tentatives: 3


sender_email:  "info.lpleboeuf@gmail.com "
recipient_email :  "info.lpleboeuf@gmail.com "
app_password : "xtmo gtar lvrb hdcq"

openweathermap:
    API_KEY: "6f5141d25c26266aa4224c7c9028432a"
    city: "Montreal"
    lang: "fr"

# les tarifs sont appeles dans le main.py et dans le pygame pour affichage
TARIFS:
    1: 4 
    2: 6 
    4: 10 
    8: 18 
    24: 30

# snt appeles dans le pygame
COLOR:
    BLUE : [10,29,121]
    WHITE : [216, 229, 253]
    BLACK : [50,50,50]
    VERT : [135,238,169]
    VERT_POMME : [128, 255, 0]
    JAUNE : [230, 249, 138]
    ORANGE : [243,133,78]
    GRIS : [160, 160, 160]
    VIOLET : [153, 51, 255]
    ROUGE : [255,0,0]
    BRUN : [153,0,0]

# sont appeles dans le pygame pour affichage
SCREEN_COLOR:
    IDLE:   VERT   
    ATTENTE ENTREE:   JAUNE   
    PAIEMENT ENTREE:   ORANGE   
    ACCES ACCEPTE:   VERT_POMME   
    STATIONNEMENT:   GRIS   
    ATTENTE SORTIE:   VIOLET   
    ERREUR:   ROUGE   
    FERME:   BRUN  
    ADMINISTRATEUR : BLACK

# sont appeles dans le pygame pour affichage
BOUTONS_PHYSIQUES:
    1:  detecte vehicule entree  
    2:  selection duree  
    3:  confirmer paiement  
    4:  detecte vehicule sortie  
    5:  annulation  
    6:  declencher erreur  
    7:  passage erreur-idle  
    8:  toggle idle-ferme 

gpio:
  capt_veh_entre: 25
  select_duree: 9
  confirm_paiement: 11
  capt_veh_sort: 5
  annul: 6
  erreur: 13
  err_idle: 19
  idle_ferme: 26

  led_verte: 14
  led_jaune: 15
  led_rouge: 18

  buzzer: 17
  servo: 27

durations:
  disponibles: [1, 2, 4, 8, 24]

journal:
    fichier: "logs/parking.log"
    niveau: "INFO"

# sont appelé par tkinter pour parametrer son affichage
auth_view:
    largeur_fenetre: 500
    hauteur_fenetre: 700
    nom_fenetre: "Parking OZ Anchois"
    texte: "Entrez votre code :"
    couleur_fond: "VERT_POMME"
    couleur_barre_titre: "BLUE"
    couleur_titre: "WHITE"
    couleur_texte: "BLACK"
    boutons_numeriques: [["1","2","3"], ["4","5","6"], ["7","8","9"], ["","0",""]]
    couleur_ecran: "WHITE"
    info_texte: 
        font_titre: Arial bold
        style_titre: "bold italic underline"
        font_texte: Arial
        font_ecran: Arial
        taille_titre: 18
        taille_texte: 14
        taille_ecran: 16 
    
